import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { registerSrcAlias } from "./lib/registerSrcAlias";
import { loadXiaohongshuCreatorProgram } from "./lib/xiaohongshuCreatorProgram";
import {
  buildXiaohongshuSeedCandidateArtifact,
  type XiaohongshuSeedCandidateInput
} from "./lib/xiaohongshuSeedCandidates";
import {
  buildXiaohongshuThumbnailOverrideMap,
  loadXiaohongshuThumbnailOverrides
} from "./lib/xiaohongshuThumbnailOverrides";

registerSrcAlias();

const OUTPUT_DIR = resolve(process.cwd(), "ops/quality");
const OUTPUT_PATH = resolve(OUTPUT_DIR, "xiaohongshu-seed-candidates.json");
const ONE_OFF_BATCH_REVIEW_LIMITS: Record<string, number> = {
  gaiao: 50,
  lingxi: 12,
  dabaiyang: 15,
  mouratoglou: 30
};

const CURATED_CANDIDATES: XiaohongshuSeedCandidateInput[] = [
  {
    creatorName: "盖奥",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5c3b619e000000000703fccc",
    creatorShortProfileUrl: "https://xhslink.com/m/3nXlLxIQQcu",
    rawUrl: "https://www.xiaohongshu.com/search_result/6436d3060000000011012067?xsec_token=ABjtcrIKBTUGC5VHoZPlC8uqeG2uhies59Bec4Jd_ACN4=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/6436d3060000000011012067",
    title: "网球正手零基础教学（详细版）",
    profileConfirmedTitle: "网球正手零基础教学（详细版）",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140054/9c86564ce9f5f35aff694ca609002d10/1000g0082b4tu69ch40005n1rc6f1vv6c0mqhrpo!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["forehand-basics"],
    teachingType: "technique_explanation",
    discoveryQuery: "网球正手零基础教学（详细版）",
    surfaceDateText: "2023-04-12",
    surfaceLikeText: "7.5万",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili forehand-teaching items from the same creator; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 1
  },
  {
    creatorName: "盖奥",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5c3b619e000000000703fccc",
    creatorShortProfileUrl: "https://xhslink.com/m/3nXlLxIQQcu",
    rawUrl: "https://www.xiaohongshu.com/search_result/69d3aa0b000000002102d993?xsec_token=ABfzlDLhHh-qf1bKp5e8QgVKwZ4kAA-CP9TmdQyMalDMw=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d3aa0b000000002102d993",
    title: "发球全要点（慢动作+细节节奏串联）",
    profileConfirmedTitle: "发球全要点（慢动作+细节节奏串联）",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140051/5310cd9155208d73f05ccd32fb5a282d/1040g2sg31ukcj0bq2ie05n1rc6f1vv6c59dtim8!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["serve-basics", "serve-rhythm"],
    teachingType: "serve",
    discoveryQuery: "发球全要点（慢动作+细节节奏串联） 盖奥",
    surfaceDateText: "04-06",
    surfaceLikeText: "1973",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili serve-teaching items from the same creator; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 2
  },
  {
    creatorName: "盖奥",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5c3b619e000000000703fccc",
    creatorShortProfileUrl: "https://xhslink.com/m/3nXlLxIQQcu",
    rawUrl: "https://www.xiaohongshu.com/search_result/69a44c1600000000150238d1?xsec_token=ABPiBbVr8jdORkqUKjP_Xg2xdZ52A9gAXMKrQKiDCk7ZE=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69a44c1600000000150238d1",
    title: "顺畅、丝滑发球的秘诀（细节全流程图）",
    profileConfirmedTitle: "顺畅、丝滑发球的秘诀（细节全流程图）",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140051/05b96dc70ad5f499051fd303b43965ca/1040g2sg31t64c8df5se05n1rc6f1vv6ctep67a0!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["serve-rhythm", "serve-timing"],
    teachingType: "serve",
    discoveryQuery: "顺畅、丝滑发球的秘诀（细节全流程图） 盖奥",
    surfaceDateText: "03-01",
    surfaceLikeText: "8843",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili serve-flow teaching items from the same creator; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 3
  },
  {
    creatorName: "盖奥",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5c3b619e000000000703fccc",
    creatorShortProfileUrl: "https://xhslink.com/m/3nXlLxIQQcu",
    rawUrl: "https://www.xiaohongshu.com/search_result/69c29c5f0000000021012666?xsec_token=ABH5hpssPelkvofgg2CnrsRvZ4iH26nWe_eqnDBttdSEU=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69c29c5f0000000021012666",
    title: "开拍慢总被球挤到？！做这6组跟练！",
    profileConfirmedTitle: "开拍慢总被球挤到？！做这6组跟练！",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140051/3f5e683c468d2ee1396c3339b93e36cb/1040g2sg31u3no0ql24e05n1rc6f1vv6ccbhktag!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["slow-preparation", "late-contact"],
    teachingType: "drill",
    discoveryQuery: "开拍慢总被球挤到？！做这6组跟练！",
    surfaceDateText: "03-24",
    surfaceLikeText: "2327",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili preparation/contact teaching items from the same creator; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 4
  },
  {
    creatorName: "盖奥",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5c3b619e000000000703fccc",
    creatorShortProfileUrl: "https://xhslink.com/m/3nXlLxIQQcu",
    rawUrl: "https://www.xiaohongshu.com/search_result/69bab756000000002102f66e?xsec_token=ABI62z72nqIPzHS_57oowbjLWDSmNv5f68F_dPYmP9s20=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69bab756000000002102f66e",
    title: "鞭打正手（单发暴击全流程拆解）",
    profileConfirmedTitle: "鞭打正手（单发暴击全流程拆解）",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140052/4ede92f89d0e41ffbbb1c722c95271f1/1040g00831ts0sf2b6u005n1rc6f1vv6cp935ivo!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["forehand-basics", "forehand-no-power"],
    teachingType: "technique_explanation",
    discoveryQuery: "鞭打正手（单发暴击全流程拆解） 盖奥",
    surfaceDateText: "03-18",
    surfaceLikeText: "2044",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili forehand-acceleration teaching items from the same creator; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 5
  },
  {
    creatorName: "灵熙🎾",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/63aef7df000000002702a346",
    creatorShortProfileUrl: "https://xhslink.com/m/2pkWMTS4aVj",
    rawUrl: "https://www.xiaohongshu.com/search_result/69dce4c6000000002301dcf1?xsec_token=AB5E2X2dR3MjVp4n5Mhl12mZY0Wy8eSVhrlU2Vr-sPHdg=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69dce4c6000000002301dcf1",
    title: "我的拦网为什么这么好？",
    profileConfirmedTitle: "我的拦网为什么这么好？",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140047/240f5e0a0397a57fef4fd17af39862bd/1040g00831utd2gnt3q005oteuvfpt8q6i4da8og!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["net-confidence"],
    teachingType: "doubles",
    discoveryQuery: "我的拦网为什么这么好 灵熙",
    surfaceDateText: "昨天 20:42",
    surfaceLikeText: "156",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "No confirmed Bilibili surface is known for this creator. Treat Xiaohongshu as the primary direct-source surface and keep this record platform-specific.",
    priority: 1
  },
  {
    creatorName: "灵熙🎾",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/63aef7df000000002702a346",
    creatorShortProfileUrl: "https://xhslink.com/m/2pkWMTS4aVj",
    rawUrl: "https://www.xiaohongshu.com/search_result/69bd3a7c000000001b020f2a?xsec_token=ABF7dcUDSTZIGsiEZF6ov9itLeVZTGrgLjK07tPTZ0-bY=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69bd3a7c000000001b020f2a",
    title: "学会这个突破脚步思路！",
    profileConfirmedTitle: "学会这个突破脚步思路！",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140042/fa1d38b9360869cd9f82c07d8d167baf/1040g00831tufj8ng7e705oteuvfpt8q6ia36ovg!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["movement-slow"],
    teachingType: "footwork",
    discoveryQuery: "学会这个突破脚步思路 灵熙",
    surfaceDateText: "03-20",
    surfaceLikeText: "888",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "No confirmed Bilibili surface is known for this creator. Treat Xiaohongshu as the primary direct-source surface and keep this record platform-specific.",
    priority: 2
  },
  {
    creatorName: "灵熙🎾",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/63aef7df000000002702a346",
    creatorShortProfileUrl: "https://xhslink.com/m/2pkWMTS4aVj",
    rawUrl: "https://www.xiaohongshu.com/search_result/69b7f9f30000000022027926?xsec_token=ABirWRNWCMiUR2qY4LXhAMVRBj9r_tj0OhPxAc6BMB6EM=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69b7f9f30000000022027926",
    title: "身体参与不够，导致失误",
    profileConfirmedTitle: "身体参与不够，导致失误",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140042/27809d67b46788e2bb995451aa93ef43/1040g2sg31tpbf4l17ee05oteuvfpt8q68edpi68!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["timing-off"],
    teachingType: "technique_explanation",
    discoveryQuery: "身体参与不够 导致失误 灵熙",
    surfaceDateText: "03-16",
    surfaceLikeText: "492",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "No confirmed Bilibili surface is known for this creator. Treat Xiaohongshu as the primary direct-source surface and keep this record platform-specific.",
    priority: 3
  },
  {
    creatorName: "灵熙🎾",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/63aef7df000000002702a346",
    creatorShortProfileUrl: "https://xhslink.com/m/2pkWMTS4aVj",
    rawUrl: "https://www.xiaohongshu.com/search_result/69c68c91000000001a0367fd?xsec_token=ABjCT_vCi2frNBGvafOQlDi4vTR9G1DxX8T8efcz4poW4=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69c68c91000000001a0367fd",
    title: "发球带点beats",
    profileConfirmedTitle: "发球带点beats",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140047/c7e4efa9ab2513085488b4137856931b/1040g00831u7ircaoio005oteuvfpt8q6qco52co!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["serve-rhythm"],
    teachingType: "serve",
    discoveryQuery: "发球带点beats 灵熙",
    surfaceDateText: "03-27",
    surfaceLikeText: "461",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "No confirmed Bilibili surface is known for this creator. Treat Xiaohongshu as the primary direct-source surface and keep this record platform-specific.",
    priority: 4
  },
  {
    creatorName: "灵熙🎾",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/63aef7df000000002702a346",
    creatorShortProfileUrl: "https://xhslink.com/m/2pkWMTS4aVj",
    rawUrl: "https://www.xiaohongshu.com/search_result/69d1af64000000001a02c33c?xsec_token=AB12ts99ayAfderyCRUCRV6wUdKjEUY_9lr2meDk9aHnQ=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d1af64000000001a02c33c",
    title: "哪个点对进攻端是至关重要的？",
    profileConfirmedTitle: "哪个点对进攻端是至关重要的？",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140047/e26249b64751ae439e4c4c132fca2c86/1040g00831uienrftig005oteuvfpt8q6htndspo!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["passive-point-construction"],
    teachingType: "tactic",
    discoveryQuery: "哪个点对进攻端是至关重要的 灵熙🎾",
    surfaceDateText: "04-05",
    surfaceLikeText: "476",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "No confirmed Bilibili surface is known for this creator. Treat Xiaohongshu as the primary direct-source surface and keep this record platform-specific.",
    priority: 5
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69bfd507000000001a033bd7?xsec_token=ABRpCaHsh6cyF4AWyPa8TB-QcG2z_WetDfxsmTD77JhpA=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69bfd507000000001a033bd7",
    title: "别学费德勒的反手",
    profileConfirmedTitle: "别学费德勒的反手",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140056/278f9b317615af03e01afb5ba5bc13d0/spectrum/1040g0k031u10u4n5gs005o2gd10g8hulunv0leg!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["backhand-basics"],
    teachingType: "technique_explanation",
    discoveryQuery: "别学费德勒的反手 莫拉托格鲁",
    surfaceDateText: "03-28",
    surfaceLikeText: "1016",
    languageHint: "mixed",
    subtitleLanguageHint: "zh_en",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou coaching clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 1
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69cbda3700000000230205b6?xsec_token=ABdb30tzXg5fUQ-t9JWNFTlKlYYWnGBjdL3e-1I4sV3uo=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69cbda3700000000230205b6",
    title: "如何正确正手发力?",
    profileConfirmedTitle: "如何正确正手发力?",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140040/7d5bdd97ac3978a6e38ea538dd52d47e/spectrum/1040g0k031ucoitn32s005o2gd10g8huln4f1tk8!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["forehand-basics", "forehand-no-power"],
    teachingType: "technique_explanation",
    discoveryQuery: "如何正确正手发力 莫拉托格鲁",
    surfaceDateText: "04-05",
    surfaceLikeText: "250",
    languageHint: "mixed",
    subtitleLanguageHint: "zh_en",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou forehand-teaching clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 2
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69c12914000000002103bec0?xsec_token=ABqn6oFUYZhU5NCmT1Sue8REVnYe0YGSjK--cTJqTgAgo=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69c12914000000002103bec0",
    title: "如何破解网前漏洞？",
    profileConfirmedTitle: "如何破解网前漏洞？",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140040/94f865684e41f47de0afa6ff335c9725/spectrum/1040g34o31u2acijp0s0g5o2gd10g8hulcuoo6c8!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["net-confidence"],
    teachingType: "tactic",
    discoveryQuery: "如何破解网前漏洞 莫拉托格鲁",
    surfaceDateText: "03-30",
    surfaceLikeText: "278",
    languageHint: "mixed",
    subtitleLanguageHint: "zh_en",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou net-play clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 3
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69cbc48a000000001f0059d4?xsec_token=ABdb30tzXg5fUQ-t9JWNFTlMNPVZ8a8YOJ17-pKOG4qas=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69cbc48a000000001f0059d4",
    title: "选手们最常犯的4个错误",
    profileConfirmedTitle: "选手们最常犯的4个错误",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140040/12a954f8d6a031c50e053155dd035fc2/spectrum/1040g0k031ucltlr6is005o2gd10g8hull8al4eo!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["general-improvement"],
    teachingType: "technique_explanation",
    discoveryQuery: "选手们最常犯的4个错误 莫拉托格鲁",
    surfaceDateText: "04-01",
    surfaceLikeText: "166",
    languageHint: "mixed",
    subtitleLanguageHint: "zh_en",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou fundamentals clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 4
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69cbc764000000001b02133b?xsec_token=ABdb30tzXg5fUQ-t9JWNFTlH5lrZcKtmy0ryLaFBmhwO0=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69cbc764000000001b02133b",
    title: "网球前四拍制胜法",
    profileConfirmedTitle: "网球前四拍制胜法",
    thumbnailUrl: "https://sns-webpic-qc.xhscdn.com/202604140041/1ef168ddd2373fcc5b77b712111d3179/spectrum/1040g34o31uf1jv6k1m0g5o2gd10g8hulf2i70vg!nc_n_nwebp_mw_1",
    preliminaryProblemTags: ["passive-point-construction"],
    teachingType: "tactic",
    discoveryQuery: "网球前四拍制胜法 莫拉托格鲁",
    surfaceDateText: "6天前",
    surfaceLikeText: "394",
    languageHint: "mixed",
    subtitleLanguageHint: "zh_en",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou point-construction clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 5
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/69bbf151000000001b003add?xsec_token=ABa2c_JziZIHzM9-y2et4sL0_FJixN9oVsnF17k8D9BdM=&xsec_source=",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69bbf151000000001b003add",
    title: "如何正确抛球？",
    profileConfirmedTitle: "如何正确抛球？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["serve-toss-consistency", "serve-basics"],
    teachingType: "serve",
    discoveryQuery: "如何正确抛球 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou serve fundamentals; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 6
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/682dc428000000001101f38d?xsec_token=ABS5AKQW7KxySu7aMJi0a53N6N1Re1K0Ii5WBRBnpMTEQ=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/682dc428000000001101f38d",
    title: "深度与角度的完美平衡｜短球处理+反手切削",
    profileConfirmedTitle: "深度与角度的完美平衡｜短球处理+反手切削",
    thumbnailUrl: null,
    preliminaryProblemTags: ["backhand-basics", "topspin-low"],
    teachingType: "technique_explanation",
    discoveryQuery: "深度与角度的完美平衡 反手切削 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou backhand technique clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 7
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/67bc408d000000002602d709?xsec_token=AB-byI3NUIE20ciZBN8MLXHNxUOkGWXfE30OARFDkj5Ko=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/67bc408d000000002602d709",
    title: "音爆密码：莫式抛球校准术解锁高速旋转杀招",
    profileConfirmedTitle: "音爆密码：莫式抛球校准术解锁高速旋转杀招",
    thumbnailUrl: null,
    preliminaryProblemTags: ["serve-toss-consistency", "serve-rhythm"],
    teachingType: "serve",
    discoveryQuery: "莫式抛球校准术 解锁 高速旋转杀招 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou serve mechanics clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 8
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/68fa1c59000000000402a60a?xsec_token=ABsB2-rOF3nc0IxGv_xKP5rWp_fPkzTptIaovIlBF5TZs=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/68fa1c59000000000402a60a",
    title: "像德约一样发球的关键",
    profileConfirmedTitle: "像德约一样发球的关键",
    thumbnailUrl: null,
    preliminaryProblemTags: ["serve-basics", "serve-toss-consistency"],
    teachingType: "serve",
    discoveryQuery: "像德约一样发球的关键 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou serve fundamentals; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 9
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/65af1f88000000002c036e46?xsec_token=ABcXZdH7nCasg4KeEvtt55nanweLlTTBSh4U7l4uRnUUA=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/65af1f88000000002c036e46",
    title: "非交叉主导型选手如何打反手球",
    profileConfirmedTitle: "非交叉主导型选手如何打反手球",
    thumbnailUrl: null,
    preliminaryProblemTags: ["backhand-basics", "running-backhand"],
    teachingType: "technique_explanation",
    discoveryQuery: "非交叉主导型选手如何打反手球 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou backhand clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 10
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/694058eb000000000d03a0ae?xsec_token=ABXSj9pCNLMUZqwoH9P43jPXrX7EVKREYURmHa1fBBJ6s=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/694058eb000000000d03a0ae",
    title: "如何打出深球？",
    profileConfirmedTitle: "如何打出深球？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["balls-too-short", "forehand-basics"],
    teachingType: "technique_explanation",
    discoveryQuery: "如何打出深球 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou rally depth clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 11
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/search_result/65ae3eff000000002c0110fd?xsec_token=AB7hci8Essq5wlcD2f8DJtnQCPrjXYVtPjtKj1MPjiqtc=&xsec_source=pc_search",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/65ae3eff000000002c0110fd",
    title: "交叉主导型选手如何打正手球",
    profileConfirmedTitle: "交叉主导型选手如何打正手球",
    thumbnailUrl: null,
    preliminaryProblemTags: ["forehand-basics", "running-forehand"],
    teachingType: "technique_explanation",
    discoveryQuery: "交叉主导型选手如何打正手球 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou forehand technique clips; keep as a separate Xiaohongshu record until manual review confirms equivalence.",
    priority: 12
  },
  {
    creatorName: "冠军教练 - 莫拉托格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69b5d8bc000000001f006be1?xsec_token=ABoSkLcUERKeRnbEcxJmkRLOieLBH52G9_g_dVdN_D68Q=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69b5d8bc000000001f006be1",
    title: "如何像德约一样接发球？",
    profileConfirmedTitle: "如何像德约一样接发球？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["return-under-pressure", "late-contact"],
    teachingType: "return",
    discoveryQuery: "如何像德约一样接发球 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; keep platform-specific until review is complete.",
    priority: 13
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69aff0410000000006030d80?xsec_token=AB2U4fm6jSzqaeqMcUBpNxwzx054c45W2RdlGBmg8wfn0=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69aff0410000000006030d80",
    title: "学习丰塞卡的发球练习",
    profileConfirmedTitle: "学习丰塞卡的发球练习",
    thumbnailUrl: null,
    preliminaryProblemTags: ["serve-rhythm", "serve-timing"],
    teachingType: "serve",
    discoveryQuery: "学习丰塞卡的发球练习 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou serve drills; keep as a separate Xiaohongshu record until review is complete.",
    priority: 14
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/699dbbcc000000001a0344a3?xsec_token=AB0WyMozOQrJiSd-PAWmD9BCXWc6WOV6LaLoCSsvk6b_o=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/699dbbcc000000001a0344a3",
    title: "【重心转移，髋部旋转】一个小调整带来的改变",
    profileConfirmedTitle: "【重心转移，髋部旋转】一个小调整带来的改变",
    thumbnailUrl: null,
    preliminaryProblemTags: ["forehand-no-power", "general-improvement"],
    teachingType: "technique_explanation",
    discoveryQuery: "重心转移 髋部旋转 一个小调整带来的改变 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; keep platform-specific until review is complete.",
    priority: 15
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/6970108f000000000a031634?xsec_token=ABEKODYHHB1Fu76bVWSEV3yr4SqxjCn6oJ9cG_haLV1Fw=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/6970108f000000000a031634",
    title: "球场上有趣的热身指导",
    profileConfirmedTitle: "球场上有趣的热身指导",
    thumbnailUrl: null,
    preliminaryProblemTags: ["general-improvement", "mobility-limit"],
    teachingType: "warmup",
    discoveryQuery: "球场上有趣的热身指导 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; treat as a direct-source warm-up item in this QA batch.",
    priority: 16
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69519b7f000000001f00feb2?xsec_token=ABo0LvwE2xxK5BDVNeYnilTkxgwG1gJm4yfShase7X6JU=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69519b7f000000001f00feb2",
    title: "如何改变握拍方式？",
    profileConfirmedTitle: "如何改变握拍方式？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["forehand-basics", "forehand-out"],
    teachingType: "technique_explanation",
    discoveryQuery: "如何改变握拍方式 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili Mouratoglou technique notes; keep as a separate Xiaohongshu record until review confirms equivalence.",
    priority: 17
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69519947000000001e00cc2f?xsec_token=ABo0LvwE2xxK5BDVNeYnilTnUKlvYJ0QCVgWyIgKCJ8WQ=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69519947000000001e00cc2f",
    title: "【心理】 当你失去信心时应怎么做？",
    profileConfirmedTitle: "【心理】 当你失去信心时应怎么做？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["pressure-tightness", "match-anxiety"],
    teachingType: "mental_execution",
    discoveryQuery: "当你失去信心时应怎么做 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; keep as a separate Xiaohongshu mental training record until review.",
    priority: 18
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69519465000000001e000043?xsec_token=ABo0LvwE2xxK5BDVNeYnilTtIok5HiHLfwmEx5o-cf2Cw=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69519465000000001e000043",
    title: "放小球全攻略",
    profileConfirmedTitle: "放小球全攻略",
    thumbnailUrl: null,
    preliminaryProblemTags: ["volley-errors", "volley-floating"],
    teachingType: "technique_explanation",
    discoveryQuery: "放小球全攻略 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili volley/approach clips; keep as a separate Xiaohongshu record until review is complete.",
    priority: 19
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/694984b4000000001e039fca?xsec_token=ABxuUt1GwmwKfF1A5obi0QvAu_m77D9zqotDzUmT0QB1I=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/694984b4000000001e039fca",
    title: "发球关键：肘部动作解析",
    profileConfirmedTitle: "发球关键：肘部动作解析",
    thumbnailUrl: null,
    preliminaryProblemTags: ["serve-basics", "serve-timing"],
    teachingType: "serve",
    discoveryQuery: "发球关键 肘部动作解析 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili serve mechanics clips; keep as a separate Xiaohongshu record until review confirms equivalence.",
    priority: 20
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/694981eb0000000019027d11?xsec_token=ABxuUt1GwmwKfF1A5obi0QvJSHXbiqV_ccM4V7ZTiCpIA=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/694981eb0000000019027d11",
    title: "为何女网选手击球要弯更低？",
    profileConfirmedTitle: "为何女网选手击球要弯更低？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["topspin-low", "general-improvement"],
    teachingType: "technique_explanation",
    discoveryQuery: "为何女网选手击球要弯更低 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili footwork/kinematics clips; keep as a separate Xiaohongshu record until review confirms equivalence.",
    priority: 21
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69519020000000001e0287fc?xsec_token=ABo0LvwE2xxK5BDVNeYnilTovZpHlgnz1soZNCNg7hWR0=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69519020000000001e0287fc",
    title: "向阿卡与纳达尔学习正手",
    profileConfirmedTitle: "向阿卡与纳达尔学习正手",
    thumbnailUrl: null,
    preliminaryProblemTags: ["forehand-basics", "forehand-out"],
    teachingType: "technique_explanation",
    discoveryQuery: "向阿卡与纳达尔学习正手 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; keep as a separate Xiaohongshu record until review is complete.",
    priority: 22
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/6949542e000000001b02423c?xsec_token=ABxuUt1GwmwKfF1A5obi0QvAeqZj_hQWv9FeNIV9EMMJI=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/6949542e000000001b02423c",
    title: "为什么击球时要放松手腕？",
    profileConfirmedTitle: "为什么击球时要放松手腕？",
    thumbnailUrl: null,
    preliminaryProblemTags: ["forehand-basics", "forehand-out"],
    teachingType: "technique_explanation",
    discoveryQuery: "为什么击球时要放松手腕 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili forehand mechanics clips; keep as a separate Xiaohongshu record until review confirms equivalence.",
    priority: 23
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/69497b9b000000000d03e873?xsec_token=ABxuUt1GwmwKfF1A5obi0QvBIPocvU2lANlQAnQGFy0iA=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69497b9b000000000d03e873",
    title: "过网高度与身体重量的正确运用",
    profileConfirmedTitle: "过网高度与身体重量的正确运用",
    thumbnailUrl: null,
    preliminaryProblemTags: ["balls-too-short", "general-improvement"],
    teachingType: "technique_explanation",
    discoveryQuery: "过网高度与身体重量的正确运用 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Potential semantic overlap with existing Bilibili groundstroke depth-control clips; keep as a separate Xiaohongshu record until review confirms equivalence.",
    priority: 24
  },
  {
    creatorName: "冠军教练 - 莫拉特格鲁",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5",
    creatorShortProfileUrl: "https://xhslink.com/m/3yjLTuwVbKr",
    rawUrl: "https://www.xiaohongshu.com/user/profile/6050684100000000010047d5/694974d4000000001f0043c0?xsec_token=ABxuUt1GwmwKfF1A5obi0QvATWDq5ftUeJhXHShA4T7Vs=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/694974d4000000001f0043c0",
    title: "【心理】消除网球场上的犹豫！",
    profileConfirmedTitle: "【心理】消除网球场上的犹豫！",
    thumbnailUrl: null,
    preliminaryProblemTags: ["pressure-tightness", "match-anxiety"],
    teachingType: "mental_execution",
    discoveryQuery: "消除网球场上的犹豫 莫拉特格鲁",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    crossPlatformNotes: "Profile-level candidate from verified Xiaohongshu source; keep as separate Xiaohongshu record until review is complete.",
    priority: 25
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/65126ff6000000001e02e3a3?xsec_token=ABWldt-qavBjH1HLBUNk6Ck2LgQ3C8iAJ_Dy6iz5LUAg8=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/65126ff6000000001e02e3a3",
    title: "网球教练，超慢的正拍慢动作",
    profileConfirmedTitle: "网球教练，超慢的正拍慢动作",
    preliminaryProblemTags: ["forehand-basics", "slow-preparation"],
    discoveryQuery: "网球教练，超慢的正拍慢动作 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 1
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69de436c00000000210069bc?xsec_token=AB08SFZxYFMQ-jANshyYzfPbF1xDRm0sW4N4_4ax5RLRk=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69de436c00000000210069bc",
    title: "网球入门&进阶请进，两个视角解析“上旋球”",
    profileConfirmedTitle: "网球入门&进阶请进，两个视角解析“上旋球”",
    preliminaryProblemTags: ["topspin-low", "forehand-basics"],
    discoveryQuery: "网球入门&进阶请进，两个视角解析“上旋球” 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 2
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69dd123c0000000023012292?xsec_token=ABmrToNDckyeGlumcPgEn6YgLIOlGXJS88M-1sJu0bDxE=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69dd123c0000000023012292",
    title: "🎾想击球“更好看”，三个小调整，推荐要试试",
    profileConfirmedTitle: "🎾想击球“更好看”，三个小调整，推荐要试试",
    preliminaryProblemTags: ["forehand-out", "timing-off"],
    discoveryQuery: "想击球更好看 三个小调整 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 3
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69db25040000000023026f89?xsec_token=ABbTmrgOM6T7qEG1Xu8IhZDoq0sXJRLk9Wgk-0dG3VD5M=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69db25040000000023026f89",
    title: "🎾增加挥拍“伸展度”，提升球质+20%",
    profileConfirmedTitle: "🎾增加挥拍“伸展度”，提升球质+20%",
    preliminaryProblemTags: ["forehand-basics", "topspin-low"],
    discoveryQuery: "增加挥拍 伸展度 提升球质 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 4
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69da46ef00000000210041e6?xsec_token=ABew6wnjUyh4xoyCX0mEkrRDRt0x39jrnJ-mAJdpiXmVQ=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69da46ef00000000210041e6",
    title: "🎾解决正拍力量“释放”，球质提升一个档次",
    profileConfirmedTitle: "🎾解决正拍力量“释放”，球质提升一个档次",
    preliminaryProblemTags: ["forehand-no-power", "forehand-basics"],
    discoveryQuery: "解决正拍力量 释放 球质提升 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "drill",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 5
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d9c58700000000210066a2?xsec_token=AB6yOKL_zxB77tWbTx1w56MVVYH2iuW9qAG19Zwm5ApCk=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d9c58700000000210066a2",
    title: "🎾击球“心流”，两个人一片场，心无杂念回击",
    profileConfirmedTitle: "🎾击球“心流”，两个人一片场，心无杂念回击",
    preliminaryProblemTags: ["match-anxiety", "pressure-tightness"],
    discoveryQuery: "击球心流 心无杂念回击 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "mental_execution",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 6
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d8c857000000001d019e71?xsec_token=ABef82l3OMUGhVNBeZKxac7C5Q0_funK9YMx0-Y-6zHw8=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d8c857000000001d019e71",
    title: "🎾理解“随上”击球，技术才能合理进阶",
    profileConfirmedTitle: "🎾理解“随上”击球，技术才能合理进阶",
    preliminaryProblemTags: ["timing-off", "slow-preparation"],
    discoveryQuery: "理解随上击球 技术进阶 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 7
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d736b9000000001b00188b?xsec_token=ABkqTodcLZXe-SyKDzCzyHqanZ_mWoTScmvaHAA157v5Q=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d736b9000000001b00188b",
    title: "4个“髋部”训练动作，练活髋！",
    profileConfirmedTitle: "4个“髋部”训练动作，练活髋！",
    preliminaryProblemTags: ["mobility-limit", "movement-slow"],
    discoveryQuery: "4个髋部 训练动作 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "drill",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 8
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d62d93000000001d019935?xsec_token=ABXqwV-uZ0vB5iB9ViajNlxZ6Igv6gENrDA5rfx7NAbZ8=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d62d93000000001d019935",
    title: "🎾三个参考要点学会把球“打深”，你都知道吗？",
    profileConfirmedTitle: "🎾三个参考要点学会把球“打深”，你都知道吗？",
    preliminaryProblemTags: ["balls-too-short", "forehand-basics"],
    discoveryQuery: "把球打深 参考要点 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "tactic",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 9
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d4eef5000000001b00184c?xsec_token=AB8gzTo2KfAV3GsW2y_4g-1cM-twnRG-ImgIoiZQRQ_0E=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d4eef5000000001b00184c",
    title: "🎾步频快才能真的快，3.0选手日常必练",
    profileConfirmedTitle: "🎾步频快才能真的快，3.0选手日常必练",
    preliminaryProblemTags: ["movement-slow", "mobility-limit"],
    discoveryQuery: "步频快才能真的快 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "footwork",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 10
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d24c780000000021004e51?xsec_token=ABB02Q8GavE0RI6M5F4YcsJj2LXt7Up1Z9n_j4J81wPcU=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d24c780000000021004e51",
    title: "发球｜🎾顺畅发球小tips，亲测有效！",
    profileConfirmedTitle: "发球｜🎾顺畅发球小tips，亲测有效！",
    preliminaryProblemTags: ["serve-rhythm", "serve-basics"],
    discoveryQuery: "顺畅发球小tips 亲测有效 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "serve",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 11
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d0e10b00000000230257be?xsec_token=ABoECiMyJEe5hHZAcEi_w2L8plucipb4DeEV3TqKHKfuA=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d0e10b00000000230257be",
    title: "🎾网球发球蓄力技巧，用“髋”发球",
    profileConfirmedTitle: "🎾网球发球蓄力技巧，用“髋”发球",
    preliminaryProblemTags: ["serve-toss-consistency", "serve-timing"],
    discoveryQuery: "网球发球蓄力技巧 用髋发球 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "serve",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 12
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69d3676e000000002200f72c?xsec_token=ABFxRRtYoO3os98uJ-xLYK8wnKOAtSEma5mz3-sLnbZyU=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69d3676e000000002200f72c",
    title: "🎾网球提升击球质量，基础必练动作",
    profileConfirmedTitle: "🎾网球提升击球质量，基础必练动作",
    preliminaryProblemTags: ["forehand-basics", "slow-preparation"],
    discoveryQuery: "提升击球质量 基础必练动作 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "drill",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 13
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69cf38490000000021005899?xsec_token=ABY0-rRVsa5vbYUTHW3lQYiH1G2ApTVklt6sbce6_vjk4=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69cf38490000000021005899",
    title: "网球击球🎾，松弛感怎么做到？？",
    profileConfirmedTitle: "网球击球🎾，松弛感怎么做到？？",
    preliminaryProblemTags: ["pressure-tightness", "general-improvement"],
    discoveryQuery: "网球击球 松弛感 怎么做到 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "technique_explanation",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 14
  },
  {
    creatorName: "奔跑的大白羊",
    creatorProfileUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853",
    rawUrl: "https://www.xiaohongshu.com/user/profile/5676c499b8ce1a5b6e806853/69b0d3a90000000026031589?xsec_token=ABfvtN2ei3HB6K_hgmFA8n4NxyzV2QJNNR47nP0sEa6Lk=&xsec_source=pc_user",
    resolvedCanonicalUrl: "https://www.xiaohongshu.com/explore/69b0d3a90000000026031589",
    title: "🎾内角一发➕截止，再老登不过了",
    profileConfirmedTitle: "🎾内角一发➕截止，再老登不过了",
    preliminaryProblemTags: ["serve-toss-consistency", "first-serve-in"],
    discoveryQuery: "内角一发 截止 再老登不过了 奔跑的大白羊",
    languageHint: "zh",
    subtitleLanguageHint: "zh",
    teachingType: "serve",
    crossPlatformNotes: "Candidate is recorded from the verified Xiaohongshu creator profile only.",
    priority: 15
  }
];

function main() {
  const creatorProgram = loadXiaohongshuCreatorProgram();
  const thumbnailOverridesByPostId = buildXiaohongshuThumbnailOverrideMap(loadXiaohongshuThumbnailOverrides());
  const artifact = buildXiaohongshuSeedCandidateArtifact({
    generatedAt: new Date().toISOString(),
    inputs: CURATED_CANDIDATES,
    creatorProgram,
    thumbnailOverridesByPostId,
    perCreatorLimitByCreatorId: ONE_OFF_BATCH_REVIEW_LIMITS
  });

  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_PATH, `${JSON.stringify(artifact, null, 2)}\n`, "utf8");

  console.log(`Wrote ${OUTPUT_PATH}`);
  for (const creator of artifact.summary.byCreator) {
    console.log(`${creator.creatorName}: saved=${creator.savedCount} target=${creator.candidateTarget} collectible=${creator.collectible}`);
  }
  console.log(`candidate_count=${artifact.summary.candidateCount}`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
